# Generated by Django 5.2.6 on 2025-10-02 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_level_code'),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='section',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='students',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='teachers',
        ),
        migrations.AddField(
            model_name='coordinator',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coordinators', to='classes.level'),
            preserve_default=False,
        ),
    ]
