# Generated by Django 5.2.6 on 2025-10-02 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short_code', models.CharField(blank=True, help_text='Short code for level (optional)', max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ('grade__level__name', 'grade__name', 'section')},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=30, help_text='Maximum students in this classroom'),
        ),
        migrations.AddField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classes.level'),
            preserve_default=False,
        ),
    ]
