# Generated by Django 5.2.6 on 2025-09-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=30, help_text='Maximum number of students allowed in this classroom'),
        ),
    ]
