# Generated by Django 5.2.6 on 2025-10-02 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_level_alter_classroom_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ('grade__name', 'section')},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='grade',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='classes.level'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
