# Generated by Django 5.2.6 on 2025-10-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classroom_options_alter_classroom_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='level',
        ),
        migrations.AddField(
            model_name='level',
            name='grades',
            field=models.ManyToManyField(blank=True, related_name='levels', to='classes.grade'),
        ),
    ]
