# Generated by Django 5.2.6 on 2025-10-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_grade_level_level_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
    ]
