# Generated by Django 5.2.5 on 2025-09-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
