# Generated by Django 5.2.6 on 2025-10-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_current_grade_student_import_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='import_file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
