# Generated by Django 5.2.6 on 2025-09-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_options_alter_student_campus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gr_no',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
