# Generated by Django 5.2.6 on 2025-09-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_student_code_alter_student_gr_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_year',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='student',
            name='shift',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
