# Generated by Django 5.2.6 on 2025-09-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('students', '0005_student_enrollment_year_student_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gr_no',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('campus', 'gr_no')},
        ),
    ]
