# Generated by Django 5.2.5 on 2025-09-26 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_current_grade_student_section'),
        ('students', '0006_alter_student_gr_no_alter_student_unique_together'),
    ]

    operations = [
    ]
