# Generated by Django 5.2.5 on 2025-09-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_merge_20250926_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['-date_enrolled']},
        ),
    ]
