# Generated by Django 5.2.5 on 2025-09-30 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('classes', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(help_text='Month (1-12)')),
                ('year', models.PositiveIntegerField(help_text='Year')),
                ('academic_year', models.CharField(help_text='Academic year', max_length=9)),
                ('total_days', models.PositiveIntegerField(default=0, help_text='Total working days in period')),
                ('present_days', models.PositiveIntegerField(default=0, help_text='Days present')),
                ('absent_days', models.PositiveIntegerField(default=0, help_text='Days absent')),
                ('late_days', models.PositiveIntegerField(default=0, help_text='Days late')),
                ('excused_days', models.PositiveIntegerField(default=0, help_text='Days excused')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Attendance percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'student__name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for which attendance is recorded')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', help_text='Attendance status of the student', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or remarks about attendance', null=True)),
                ('excuse_reason', models.CharField(blank=True, help_text='Reason for absence or late arrival', max_length=200, null=True)),
                ('excuse_document', models.FileField(blank=True, help_text='Upload excuse letter or medical certificate', null=True, upload_to='attendance/excuses/')),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024-2025)', max_length=9)),
                ('semester', models.CharField(blank=True, help_text='Semester or term (e.g., First Term, Second Term)', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(help_text='Campus where attendance is recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='campus.campus')),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Class teacher who marked the attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_attendances', to='teachers.teacher')),
                ('classroom', models.ForeignKey(help_text='Class (Grade + Section) for which attendance is recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.classroom')),
            ],
            options={
                'ordering': ['-date', 'student__name'],
            },
        ),
    ]
