# Generated by Django 5.2.6 on 2025-10-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_rename_address_campus_address_full_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='If True, campus is in draft mode'),
        ),
    ]
